---
- name: Setup workstation environment
  hosts: all
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
  - common
  - php
  - composer
  - mariadb
  - nodejs
  - vscode