---
- name: Setup workstation
  hosts: localhost
  connection: local
  gather_facts: yes
  become_method: sudo
  vars:
    current_user: "{{ ansible_user_id }}"
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - software-properties-common
          - build-essential
          - curl
          - wget
          - git
          - make
          - python3
          - python3-pip
          - ufw
          - zip
          - unzip
          - whois
          - zsh
          - htop
      become: true

  roles:
    - php
    - composer
    - nodejs
    - mysql
    - alacritty
    - tmux
    - vscode
    - ohmyzsh
    # - brave
    # - enpass
    # - 1password
    # - chrome
    # - vlc

  post_tasks:
    - name: Cleanup
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
      become: true
