---
- name: Setup workstation
  hosts: localhost
  connection: local
  gather_facts: true
  become_method: sudo
  vars:
    current_user: "{{ ansible_user_id }}"
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_distribution_release
      tags: [debug]

    - name: Update system
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - software-properties-common
          - ca-certificates
          - gnupg
          - lsb-release
          - build-essential
          - curl
          - wget
          - git
          - make
          - python3
          - python3-pip
          - ufw
          - zip
          - unzip
          - whois
          - zsh
          - htop
          - tar
          - vlc
          - newsboat
      become: true

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - awscli
        state: present
        extra_args: '--user'
      tags: [pip]

  roles:
    # - php
    # - composer
    - nodejs
    # - mysql
    # - alacritty
    - tmux
    - role: vscode
      tags: [ide]
    - ohmyzsh
    - brave
    - enpass
    - telegram
    - 1password
    - chrome
    - terraform
    - role: docker
      tags: [docker]
    - role: blender
      tags: [3d]
    - role: godot
      tags: [godot]
    # - qbittorrent
    # - lutris
    # - discord
    # - youtube-dl
    # - libreoffice
    # - calibre

  post_tasks:
    - name: Cleanup
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
      become: true
