---
# roles/vscode/tasks/main.yml

- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install VSCode
  apt:
    name: code
    state: present
    update_cache: true

- name: Install VSCode extensions
  command: "code --install-extension {{ item }}"
  when: (vscode_extensions is defined) and (vscode_extensions) and (vscode_extensions|length > 0)
  with_items: "{{ vscode_extensions }}"
  become: false
