---
- name: Add Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: Add VSCode repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  become: true

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    state: present
  become: true

- name: Install VSCode extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  when: (vscode_extensions is defined) and (vscode_extensions) and (vscode_extensions|length > 0)
  with_items: "{{ vscode_extensions }}"
  register: vscode_extension
  changed_when: "'was successfully installed' in vscode_extension.stdout"
