---
- name: Clone Oh My ZSH repo
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "~/.oh-my-zsh"
    version: master

- name: Link ZSH resource file
  ansible.builtin.file:
    src: "{{ role_path }}/files/zshrc"
    dest: ~/.zshrc
    state: link
    force: true

- name: Set default shell to ZSH
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: /bin/zsh
  become: true
