---
- name: Add NodeJs APT repo GPG key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /usr/share/keyrings/nodesource.gpg
    state: present
  become: true

- name: Add NodeJs APT repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource
  become: true

- name: Install NodeJs
  ansible.builtin.apt:
    name: nodejs
    state: present
  become: true
