---
# roles/mariadb/tasks/main.yml

- name: Download MariaDB setup
  get_url:
    url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    dest: /tmp/mariadb_repo_setup
  become: false

- name: Install MariaDB repository
  command: bash /tmp/mariadb_repo_setup

- name: Install MariaDB
  apt:
    pkg:
    - mariadb-client
    - mariadb-server
    state: present
    update_cache: true