---
# tasks file for ansible-role-composer
- name: Download Composer checksum
  ansible.builtin.uri:
    url: https://getcomposer.org/composer-stable.phar.sha256
    return_content: true
    force: true
  register: composer_checksum_response

- name: Download and install Composer binary
  ansible.builtin.get_url:
    url: 'https://getcomposer.org/composer-stable.phar'
    checksum: "sha256:{{ composer_checksum_response.content }}"
    dest: "/usr/bin/composer"
  become: true

- name: Make binary executable
  ansible.builtin.file:
    path: "/usr/bin/composer"
    mode: +x
  become: true
