---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present
  become: true

- name: Install PHP
  ansible.builtin.apt:
    name:
      - "php{{ item }}"
      - "php{{ item }}-fpm"
      - "php{{ item }}-cli"
      - "php{{ item }}-mbstring"
      - "php{{ item }}-bcmath"
      - "php{{ item }}-pgsql"
      - "php{{ item }}-mysql"
      - "php{{ item }}-sqlite3"
      - "php{{ item }}-xml"
      - "php{{ item }}-zip"
      - "php{{ item }}-intl"
      - "php{{ item }}-curl"
      - "php{{ item }}-imagick"
      - "php{{ item }}-gd"
      - "php{{ item }}-readline"
    state: present
  loop: "{{ php_versions }}"
  become: true

- name: Set default PHP
  ansible.builtin.alternatives:
    name: php
    path: "/usr/bin/php{{ default_php_version }}"
  become: true
