---
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP
  apt:
    pkg:
    - "php{{ php_version }}"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-pgsql"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-sqlite3"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-curl"
    state: present
    update_cache: true